### ISSUE TITLE
Conflic when deploying war file

### ISSUE THREAD

**Issue by MichaelC753** [eclipse-emfcloud/emfjson-jackson#23]
Hello, I think I have a conflict when I'm trying to deploy a web application with a dependancy with emf-jackson 2.0.0
I tried several servers, I'm currently trying with wildfly-26.0.0.Final
Everything is working as excepted if I just package everything as a jar with springboot.

The error : 
` Forwarding to error page from request [/rest/v1/files/c04fd2e2-07d1-447d-a2aa-d2778ae10473] due to exception [Cannot create resource for uri default]: java.lang.RuntimeException: Cannot create resource for uri default
        at deployment.app-ws-2022-18-01.war//org.eclipse.emfcloud.jackson.databind.deser.ResourceDeserializer.getResource(ResourceDeserializer.java:95)
        at deployment.app-ws-2022-18-01.war//org.eclipse.emfcloud.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:50)
        at deployment.app-ws-2022-18-01.war//org.eclipse.emfcloud.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:43)
        at deployment.app-ws-2022-18-01.war//org.eclipse.emfcloud.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:30)
        at deployment.app-ws-2022-18-01.war//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at deployment.app-ws-2022-18-01.war//com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
        at deployment.app-ws-2022-18-01.war//com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1491)`

I tried to add a jboss-deployment-structure.xml to resolve the conflict with but it does nothing to solve the issue.

`<jboss-deployment-structure>
    <deployment>
        <exclusions>
            <module name="com.fasterxml.jackson.core.jackson-core" />
            <module name="com.fasterxml.jackson.core.jackson-databind" />
            <module name="com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider" />
            <module name="org.jboss.resteasy.resteasy-jackson2-provider" />
            <module name="com.fasterxml.jackson.datatype.jackson-datatype-jdk8" />
            <module name="com.fasterxml.jackson.datatype.jackson-datatype-jsr310" />
        </exclusions>
    </deployment>
</jboss-deployment-structure>`

Any help for using the library in a war file would be really appreciate.

Regards,

**Comment by eneufeld** [comment]
Sorry for the late reply. I hope you could resolve your issue. But I'm rather clueless how to fix this ;-) .
